Fix uninitialized constant `Hiera::Backend::Eyaml::Encryptors::GpgVersion`
Not sure why this wasn't a problem when testing `eyaml version -n gpg`,
but without this `require` the gem is unuseable on the puppetserver :(

With this fix, everything, (finally), seems ok on the puppetserver.

Fixes
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, uninitialized constant Hiera::Backend::Eyaml::Encryptors::GpgVersion
```